### ISSUE TITLE
Performance issue in Firefox due to new KDE integration

### ISSUE THREAD

**Issue by dlichtenberger** [libproxy/libproxy#16] opened 2016-02-13 11:21 UTC
I stumbled over a performance regression in Firefox 44 with KDE 5 (openSUSE Tumbleweed) that seems to be related to libproxy 0.4.12. Pages with many resources ([test 1](http://derstandard.at/Web), [test 2](http://derstandard.at/Etat)) take painfully long to render (up to 10 seconds with high CPU usage). 

A bit of profiling reveals that Firefox invokes kreadconfig5 *many* times for a single page - it seems like the proxy configuration is retrieved for every resource, and that the new KDE integration in libproxy 0.4.12 does not perform well under these circumstances.

Setting the proxy in Firefox to "none" (instead of the default "use system settings") fixes the issue.

**Comment by DimStar77** [comment] 2016-02-15 09:29
Thank you very much for the report!
@Vogtinator would this be something you could look into? The KDE plugin needs a better way to monitor for changes without spawning kdeconfig all the time (we need to know about changes, but not get the info for every resource)

**Comment by Vogtinator** [comment] 2016-02-15 14:05
Although I thought about performance issues, I didn't think that it could become such a problem.
I "benchmarked" kreadconfig with time in a loop and it takes around 7 ms each run.
kreadconfig5 is much faster, around 2 ms. That shouldn't be causing those massive delays.

Without loosing the flexibility of no link-time dependencies it's not possible to improve that further, I'm afraid.

**Comment by DimStar77** [comment] 2016-02-15 14:09
Then we need to have an own implementation of a caching daemon as is done for GNOME (pxgsettings) which can link whatever it wants, as it communicates with the actual libproxy over stdin/stdout, thus bringing the linking problem out of the original application scope.

**Comment by Vogtinator** [comment] 2016-02-15 14:24
Currently the bottleneck is probably invoking the shell through popen. By replacing that with the much quicker but also slightly less convenient fork(), mkpipe(...) and execv(...), that could be improved significantly, but not as much as caching would do.
Also, calling libproxy for every single resource on a page is a bit too much, once for every origin (protocol + domain) should be enough. Does libproxy feature a cache that could be used to avoid making unnecessary queries? By comparing the timestamp of the configuration file (inotify not required IMO) invalidating it shouldn't be an issue.

**Comment by DimStar77** [comment] 2016-02-15 14:25
calling libproxy for every esource is by design and mandatory:
a pac parser script might well redirect between different caching proxies based on url/content tyoe.

**Comment by Vogtinator** [comment] 2016-02-15 14:31
If PAC is not enabled it's not necessary then, so libproxy might as well cache the values automatically, until a method "needsUpdate()" or similiar in a plugin returns true.
That could be done in the plugin itself as well (pretty easily even, by storing the values from kreadconfig in a hash), but general support is better IMHO.

**Comment by DimStar77** [comment] 2016-02-15 14:34
the plugin is the only one that must cache! the user can change between one mode and the other while an app is running - if libproxy were to cache values and config states, we would miss change events. The plugin is the one having the right information at hand.

**Comment by Vogtinator** [comment] 2016-02-15 14:34
> if libproxy were to cache values and config states, we would miss change events.

That's exactly what the "needsUpdate()" method would avoid.

**Comment by DimStar77** [comment] 2016-02-15 14:38
you really want to change the entire internal design now and every single plugin out there? I think that's a bad idea... 

Really, have a look at how pxgsettings and the config_gnome3 module interact together.

you can easily start pxgsettings with:
/usr/lib/libproxy-0.4.12/pxgsettings org.gnome.system.proxy.http

it will output the 'current' configuration parameters as configured there.
the values are consumed and cached by config_gnome3

any change in the dconf database triggers notificatins to pxgsettings, which outputs the new data immediately (while the user types there are multiple events, but that's acceptable)

the config_gnome3 plugin keeps on getting the life data.

**Comment by Vogtinator** [comment] 2016-02-15 14:43
The general caching doesn't really fit all modules then, it seems.
I'll look into adding a cache to the kde module then.

**Comment by Vogtinator** [comment] 2016-02-16 21:19
@dlichtenberger Can you confirm that PR #17 fixes your issue?

**Comment by dlichtenberger** [comment] 2016-02-18 17:02
Yes, the performance issue is fixed - and KDE (5) proxy settings are used as expected. Thanks for the quick response!

**Comment by DimStar77** [comment] 2016-03-23 14:37
Fix has been merged - we'll have to prepare a release soon again it seems

**Closed by DimStar77** 2016-03-23 14:37 UTC
